apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::312651556977:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-12RCXQRCBOIMV
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::312651556977:role/UdacityFlaskDeployCBKubectlRole
      username: build      
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::312651556977:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17C402QC9VF6L
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-16T09:59:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1566"
  uid: ff0cb54d-fae7-4b50-addf-2af251dec14a
